// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cnode/container.proto

package proto_cnode_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateStatus int32

const (
	CreateStatus_Loading       CreateStatus = 0
	CreateStatus_PullImage     CreateStatus = 1
	CreateStatus_StartCreate   CreateStatus = 2
	CreateStatus_CreateSuccess CreateStatus = 3
	CreateStatus_CreateError   CreateStatus = 4
	CreateStatus_Delete        CreateStatus = 5
)

var CreateStatus_name = map[int32]string{
	0: "Loading",
	1: "PullImage",
	2: "StartCreate",
	3: "CreateSuccess",
	4: "CreateError",
	5: "Delete",
}

var CreateStatus_value = map[string]int32{
	"Loading":       0,
	"PullImage":     1,
	"StartCreate":   2,
	"CreateSuccess": 3,
	"CreateError":   4,
	"Delete":        5,
}

func (x CreateStatus) String() string {
	return proto.EnumName(CreateStatus_name, int32(x))
}

func (CreateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{0}
}

type CallType int32

const (
	CallType_CreateContainer CallType = 0
	CallType_GetContainer    CallType = 1
)

var CallType_name = map[int32]string{
	0: "CreateContainer",
	1: "GetContainer",
}

var CallType_value = map[string]int32{
	"CreateContainer": 0,
	"GetContainer":    1,
}

func (x CallType) String() string {
	return proto.EnumName(CallType_name, int32(x))
}

func (CallType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{1}
}

type CreateConfig struct {
	Image                string   `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	Cmd                  string   `protobuf:"bytes,2,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	NetworkDisabled      bool     `protobuf:"varint,3,opt,name=NetworkDisabled,proto3" json:"NetworkDisabled,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=HostName,proto3" json:"HostName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConfig) Reset()         { *m = CreateConfig{} }
func (m *CreateConfig) String() string { return proto.CompactTextString(m) }
func (*CreateConfig) ProtoMessage()    {}
func (*CreateConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{0}
}

func (m *CreateConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConfig.Unmarshal(m, b)
}
func (m *CreateConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConfig.Marshal(b, m, deterministic)
}
func (m *CreateConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConfig.Merge(m, src)
}
func (m *CreateConfig) XXX_Size() int {
	return xxx_messageInfo_CreateConfig.Size(m)
}
func (m *CreateConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConfig proto.InternalMessageInfo

func (m *CreateConfig) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateConfig) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *CreateConfig) GetNetworkDisabled() bool {
	if m != nil {
		return m.NetworkDisabled
	}
	return false
}

func (m *CreateConfig) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

type ThrottleDevice struct {
	Path                 string   `protobuf:"bytes,1,opt,name=Path,proto3" json:"Path,omitempty"`
	Rate                 uint64   `protobuf:"varint,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThrottleDevice) Reset()         { *m = ThrottleDevice{} }
func (m *ThrottleDevice) String() string { return proto.CompactTextString(m) }
func (*ThrottleDevice) ProtoMessage()    {}
func (*ThrottleDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{1}
}

func (m *ThrottleDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThrottleDevice.Unmarshal(m, b)
}
func (m *ThrottleDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThrottleDevice.Marshal(b, m, deterministic)
}
func (m *ThrottleDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThrottleDevice.Merge(m, src)
}
func (m *ThrottleDevice) XXX_Size() int {
	return xxx_messageInfo_ThrottleDevice.Size(m)
}
func (m *ThrottleDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_ThrottleDevice.DiscardUnknown(m)
}

var xxx_messageInfo_ThrottleDevice proto.InternalMessageInfo

func (m *ThrottleDevice) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ThrottleDevice) GetRate() uint64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type Resources struct {
	AutoRemove           bool            `protobuf:"varint,1,opt,name=AutoRemove,proto3" json:"AutoRemove,omitempty"`
	Memory               int64           `protobuf:"varint,2,opt,name=Memory,proto3" json:"Memory,omitempty"`
	KernelMemoryTCP      int64           `protobuf:"varint,5,opt,name=KernelMemoryTCP,proto3" json:"KernelMemoryTCP,omitempty"`
	BlkioDeviceReadBps   *ThrottleDevice `protobuf:"bytes,3,opt,name=BlkioDeviceReadBps,proto3" json:"BlkioDeviceReadBps,omitempty"`
	BlkioDeviceWriteBps  *ThrottleDevice `protobuf:"bytes,4,opt,name=BlkioDeviceWriteBps,proto3" json:"BlkioDeviceWriteBps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Resources) Reset()         { *m = Resources{} }
func (m *Resources) String() string { return proto.CompactTextString(m) }
func (*Resources) ProtoMessage()    {}
func (*Resources) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{2}
}

func (m *Resources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resources.Unmarshal(m, b)
}
func (m *Resources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resources.Marshal(b, m, deterministic)
}
func (m *Resources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resources.Merge(m, src)
}
func (m *Resources) XXX_Size() int {
	return xxx_messageInfo_Resources.Size(m)
}
func (m *Resources) XXX_DiscardUnknown() {
	xxx_messageInfo_Resources.DiscardUnknown(m)
}

var xxx_messageInfo_Resources proto.InternalMessageInfo

func (m *Resources) GetAutoRemove() bool {
	if m != nil {
		return m.AutoRemove
	}
	return false
}

func (m *Resources) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Resources) GetKernelMemoryTCP() int64 {
	if m != nil {
		return m.KernelMemoryTCP
	}
	return 0
}

func (m *Resources) GetBlkioDeviceReadBps() *ThrottleDevice {
	if m != nil {
		return m.BlkioDeviceReadBps
	}
	return nil
}

func (m *Resources) GetBlkioDeviceWriteBps() *ThrottleDevice {
	if m != nil {
		return m.BlkioDeviceWriteBps
	}
	return nil
}

type CallOpt struct {
	Type                 CallType   `protobuf:"varint,1,opt,name=type,proto3,enum=proto.cnode.service.CallType" json:"type,omitempty"`
	Create               *CreateOpt `protobuf:"bytes,2,opt,name=create,proto3" json:"create,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CallOpt) Reset()         { *m = CallOpt{} }
func (m *CallOpt) String() string { return proto.CompactTextString(m) }
func (*CallOpt) ProtoMessage()    {}
func (*CallOpt) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{3}
}

func (m *CallOpt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallOpt.Unmarshal(m, b)
}
func (m *CallOpt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallOpt.Marshal(b, m, deterministic)
}
func (m *CallOpt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallOpt.Merge(m, src)
}
func (m *CallOpt) XXX_Size() int {
	return xxx_messageInfo_CallOpt.Size(m)
}
func (m *CallOpt) XXX_DiscardUnknown() {
	xxx_messageInfo_CallOpt.DiscardUnknown(m)
}

var xxx_messageInfo_CallOpt proto.InternalMessageInfo

func (m *CallOpt) GetType() CallType {
	if m != nil {
		return m.Type
	}
	return CallType_CreateContainer
}

func (m *CallOpt) GetCreate() *CreateOpt {
	if m != nil {
		return m.Create
	}
	return nil
}

type CreateOpt struct {
	Config               *CreateConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Resources            *Resources    `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Cid                  string        `protobuf:"bytes,3,opt,name=Cid,proto3" json:"Cid,omitempty"`
	Status               CreateStatus  `protobuf:"varint,4,opt,name=status,proto3,enum=proto.cnode.service.CreateStatus" json:"status,omitempty"`
	QueueMsgTime         uint64        `protobuf:"varint,5,opt,name=QueueMsgTime,proto3" json:"QueueMsgTime,omitempty"`
	Uid                  uint64        `protobuf:"varint,6,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateOpt) Reset()         { *m = CreateOpt{} }
func (m *CreateOpt) String() string { return proto.CompactTextString(m) }
func (*CreateOpt) ProtoMessage()    {}
func (*CreateOpt) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{4}
}

func (m *CreateOpt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOpt.Unmarshal(m, b)
}
func (m *CreateOpt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOpt.Marshal(b, m, deterministic)
}
func (m *CreateOpt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOpt.Merge(m, src)
}
func (m *CreateOpt) XXX_Size() int {
	return xxx_messageInfo_CreateOpt.Size(m)
}
func (m *CreateOpt) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOpt.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOpt proto.InternalMessageInfo

func (m *CreateOpt) GetConfig() *CreateConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *CreateOpt) GetResources() *Resources {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *CreateOpt) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *CreateOpt) GetStatus() CreateStatus {
	if m != nil {
		return m.Status
	}
	return CreateStatus_Loading
}

func (m *CreateOpt) GetQueueMsgTime() uint64 {
	if m != nil {
		return m.QueueMsgTime
	}
	return 0
}

func (m *CreateOpt) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type CreateNotice struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNotice) Reset()         { *m = CreateNotice{} }
func (m *CreateNotice) String() string { return proto.CompactTextString(m) }
func (*CreateNotice) ProtoMessage()    {}
func (*CreateNotice) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{5}
}

func (m *CreateNotice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotice.Unmarshal(m, b)
}
func (m *CreateNotice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotice.Marshal(b, m, deterministic)
}
func (m *CreateNotice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotice.Merge(m, src)
}
func (m *CreateNotice) XXX_Size() int {
	return xxx_messageInfo_CreateNotice.Size(m)
}
func (m *CreateNotice) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotice.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotice proto.InternalMessageInfo

func (m *CreateNotice) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type CreateRsp struct {
	Ack                  bool     `protobuf:"varint,1,opt,name=Ack,proto3" json:"Ack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRsp) Reset()         { *m = CreateRsp{} }
func (m *CreateRsp) String() string { return proto.CompactTextString(m) }
func (*CreateRsp) ProtoMessage()    {}
func (*CreateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{6}
}

func (m *CreateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRsp.Unmarshal(m, b)
}
func (m *CreateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRsp.Marshal(b, m, deterministic)
}
func (m *CreateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRsp.Merge(m, src)
}
func (m *CreateRsp) XXX_Size() int {
	return xxx_messageInfo_CreateRsp.Size(m)
}
func (m *CreateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRsp proto.InternalMessageInfo

func (m *CreateRsp) GetAck() bool {
	if m != nil {
		return m.Ack
	}
	return false
}

type CallRsp struct {
	Status               bool     `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallRsp) Reset()         { *m = CallRsp{} }
func (m *CallRsp) String() string { return proto.CompactTextString(m) }
func (*CallRsp) ProtoMessage()    {}
func (*CallRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a167533b2d6728ca, []int{7}
}

func (m *CallRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallRsp.Unmarshal(m, b)
}
func (m *CallRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallRsp.Marshal(b, m, deterministic)
}
func (m *CallRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallRsp.Merge(m, src)
}
func (m *CallRsp) XXX_Size() int {
	return xxx_messageInfo_CallRsp.Size(m)
}
func (m *CallRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CallRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CallRsp proto.InternalMessageInfo

func (m *CallRsp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CallRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CallRsp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.cnode.service.CreateStatus", CreateStatus_name, CreateStatus_value)
	proto.RegisterEnum("proto.cnode.service.CallType", CallType_name, CallType_value)
	proto.RegisterType((*CreateConfig)(nil), "proto.cnode.service.CreateConfig")
	proto.RegisterType((*ThrottleDevice)(nil), "proto.cnode.service.ThrottleDevice")
	proto.RegisterType((*Resources)(nil), "proto.cnode.service.Resources")
	proto.RegisterType((*CallOpt)(nil), "proto.cnode.service.CallOpt")
	proto.RegisterType((*CreateOpt)(nil), "proto.cnode.service.CreateOpt")
	proto.RegisterType((*CreateNotice)(nil), "proto.cnode.service.CreateNotice")
	proto.RegisterType((*CreateRsp)(nil), "proto.cnode.service.CreateRsp")
	proto.RegisterType((*CallRsp)(nil), "proto.cnode.service.CallRsp")
}

func init() { proto.RegisterFile("proto/cnode/container.proto", fileDescriptor_a167533b2d6728ca) }

var fileDescriptor_a167533b2d6728ca = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x4f, 0xdb, 0x4c,
	0x10, 0xc6, 0x89, 0x31, 0xc9, 0x84, 0x0f, 0xbf, 0xcb, 0x2b, 0x14, 0xd1, 0x82, 0xa8, 0x7b, 0x41,
	0x1c, 0x82, 0x48, 0xa5, 0xaa, 0x95, 0x7a, 0x81, 0x80, 0x68, 0xd5, 0x12, 0xe8, 0x26, 0xa8, 0xe7,
	0xc5, 0x9e, 0x1a, 0x2b, 0xb6, 0xd7, 0xda, 0x5d, 0x53, 0x45, 0xea, 0xbd, 0xbf, 0xa1, 0x87, 0xfe,
	0xd7, 0x6a, 0x77, 0xed, 0xf0, 0xa1, 0x10, 0xf5, 0xe4, 0x99, 0x67, 0x3e, 0xf6, 0xd9, 0x99, 0x67,
	0x0d, 0x2f, 0x0a, 0xc1, 0x15, 0x3f, 0x0c, 0x73, 0x1e, 0xe1, 0x61, 0xc8, 0x73, 0xc5, 0x92, 0x1c,
	0x45, 0xcf, 0xa0, 0x64, 0xd3, 0x7c, 0x7a, 0x26, 0xd8, 0x93, 0x28, 0xee, 0x92, 0x10, 0x83, 0x9f,
	0xb0, 0x3a, 0x10, 0xc8, 0x14, 0x0e, 0x78, 0xfe, 0x3d, 0x89, 0xc9, 0xff, 0xb0, 0xfc, 0x29, 0x63,
	0x31, 0x76, 0x9d, 0x3d, 0x67, 0xbf, 0x4d, 0xad, 0x43, 0x7c, 0x68, 0x0e, 0xb2, 0xa8, 0xdb, 0x30,
	0x98, 0x36, 0xc9, 0x3e, 0x6c, 0x0c, 0x51, 0xfd, 0xe0, 0x62, 0x72, 0x9a, 0x48, 0x76, 0x93, 0x62,
	0xd4, 0x6d, 0xee, 0x39, 0xfb, 0x2d, 0xfa, 0x14, 0x26, 0xdb, 0xd0, 0xfa, 0xc8, 0xa5, 0x1a, 0xb2,
	0x0c, 0xbb, 0xae, 0x69, 0x30, 0xf3, 0x83, 0x77, 0xb0, 0x3e, 0xbe, 0x15, 0x5c, 0xa9, 0x14, 0x4f,
	0x51, 0xf3, 0x21, 0x04, 0xdc, 0x2b, 0xa6, 0x6e, 0xab, 0xe3, 0x8d, 0xad, 0x31, 0xca, 0x14, 0x9a,
	0xe3, 0x5d, 0x6a, 0xec, 0xe0, 0x77, 0x03, 0xda, 0x14, 0x25, 0x2f, 0x45, 0x88, 0x92, 0xec, 0x02,
	0x1c, 0x97, 0x8a, 0x53, 0xcc, 0xf8, 0x9d, 0xa5, 0xde, 0xa2, 0x0f, 0x10, 0xb2, 0x05, 0xde, 0x05,
	0x66, 0x5c, 0x4c, 0x4d, 0x8f, 0x26, 0xad, 0x3c, 0x7d, 0x8b, 0xcf, 0x28, 0x72, 0x4c, 0xad, 0x3f,
	0x1e, 0x5c, 0x75, 0x97, 0x4d, 0xc2, 0x53, 0x98, 0x8c, 0x80, 0x9c, 0xa4, 0x93, 0x84, 0x5b, 0x9a,
	0x14, 0x59, 0x74, 0x52, 0x48, 0x73, 0xe5, 0x4e, 0xff, 0x75, 0x6f, 0xce, 0x64, 0x7b, 0x8f, 0x2f,
	0x46, 0xe7, 0x94, 0x93, 0x6b, 0xd8, 0x7c, 0x80, 0x7e, 0x13, 0x89, 0x42, 0xdd, 0xd5, 0xfd, 0xf7,
	0xae, 0xf3, 0xea, 0x03, 0x05, 0x2b, 0x03, 0x96, 0xa6, 0x97, 0x85, 0x22, 0x47, 0xe0, 0xaa, 0x69,
	0x61, 0x47, 0xb2, 0xde, 0xdf, 0x99, 0xdb, 0x52, 0xe7, 0x8e, 0xa7, 0x05, 0x52, 0x93, 0x4a, 0xde,
	0x82, 0x17, 0x1a, 0x45, 0x98, 0x59, 0x75, 0xfa, 0xbb, 0xf3, 0x8b, 0x4c, 0xca, 0x65, 0xa1, 0x68,
	0x95, 0x1d, 0xfc, 0x6a, 0x40, 0x7b, 0x86, 0x92, 0xf7, 0xe0, 0x85, 0x46, 0x51, 0xe6, 0xe8, 0x4e,
	0xff, 0xd5, 0x82, 0x2e, 0x56, 0x7a, 0xb4, 0x2a, 0x20, 0x1f, 0xa0, 0x2d, 0xea, 0xcd, 0x2e, 0xe4,
	0x30, 0xdb, 0x3f, 0xbd, 0x2f, 0x30, 0x52, 0x4d, 0xac, 0x18, 0xb5, 0x54, 0x93, 0x48, 0x53, 0x91,
	0x8a, 0xa9, 0xd2, 0x0e, 0x76, 0x7d, 0x21, 0x95, 0x91, 0x49, 0xa4, 0x55, 0x01, 0x09, 0x60, 0xf5,
	0x6b, 0x89, 0x25, 0x5e, 0xc8, 0x78, 0x9c, 0x64, 0x68, 0xc4, 0xe1, 0xd2, 0x47, 0x98, 0x3e, 0xf0,
	0x3a, 0x89, 0xba, 0x9e, 0x09, 0x69, 0x33, 0xd8, 0xab, 0xdf, 0xd4, 0x90, 0x2b, 0xad, 0xe9, 0x8a,
	0x92, 0x33, 0xa3, 0x14, 0xec, 0xd4, 0xa3, 0xa2, 0xb2, 0xd0, 0xe1, 0xe3, 0x70, 0x52, 0xa9, 0x56,
	0x9b, 0xc1, 0xb9, 0x5d, 0xa0, 0x0e, 0x6e, 0x81, 0x67, 0x39, 0x55, 0xf1, 0xca, 0xd3, 0x45, 0x99,
	0x8c, 0xeb, 0x17, 0x99, 0xc9, 0x58, 0xbf, 0x92, 0x88, 0x29, 0x56, 0xdd, 0xdc, 0xd8, 0x07, 0x93,
	0x9a, 0x49, 0x55, 0xd5, 0x81, 0x95, 0x2f, 0x9c, 0x45, 0x49, 0x1e, 0xfb, 0x4b, 0x64, 0x0d, 0xda,
	0x57, 0x65, 0x9a, 0x9a, 0x17, 0xee, 0x3b, 0x64, 0x03, 0x3a, 0x23, 0xc5, 0x84, 0xb2, 0x05, 0x7e,
	0x83, 0xfc, 0x07, 0x6b, 0x55, 0x71, 0x19, 0x86, 0x28, 0xa5, 0xdf, 0xd4, 0x39, 0x16, 0x3a, 0x13,
	0x82, 0x0b, 0xdf, 0x25, 0x00, 0xde, 0x29, 0xa6, 0xa8, 0xd0, 0x5f, 0x3e, 0x38, 0x82, 0x56, 0x2d,
	0x25, 0xb2, 0x09, 0x1b, 0xb3, 0xdd, 0xda, 0x9f, 0x90, 0xbf, 0x44, 0x7c, 0x58, 0x3d, 0x47, 0x75,
	0x8f, 0x38, 0xfd, 0x3f, 0x0e, 0xb8, 0x43, 0x1e, 0x21, 0x39, 0x83, 0x95, 0x91, 0x5d, 0x04, 0x79,
	0xf9, 0xac, 0x48, 0x2f, 0x0b, 0xb5, 0xfd, 0x7c, 0x54, 0x4f, 0x6b, 0x58, 0xcf, 0xf5, 0x42, 0xc6,
	0x64, 0xd1, 0x9e, 0xed, 0x66, 0xb6, 0x17, 0x69, 0x9b, 0xca, 0xe2, 0xc6, 0x33, 0xe1, 0x37, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x78, 0x2a, 0xb6, 0x7b, 0x58, 0x05, 0x00, 0x00,
}
