// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/status.proto

package server_status

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetStatus service

type GetStatusService interface {
	Status(ctx context.Context, in *GetStatus, opts ...client.CallOption) (*RetStatus, error)
}

type getStatusService struct {
	c    client.Client
	name string
}

func NewGetStatusService(name string, c client.Client) GetStatusService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "server.status"
	}
	return &getStatusService{
		c:    c,
		name: name,
	}
}

func (c *getStatusService) Status(ctx context.Context, in *GetStatus, opts ...client.CallOption) (*RetStatus, error) {
	req := c.c.NewRequest(c.name, "GetStatus.Status", in)
	out := new(RetStatus)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetStatus service

type GetStatusHandler interface {
	Status(context.Context, *GetStatus, *RetStatus) error
}

func RegisterGetStatusHandler(s server.Server, hdlr GetStatusHandler, opts ...server.HandlerOption) error {
	type getStatus interface {
		Status(ctx context.Context, in *GetStatus, out *RetStatus) error
	}
	type GetStatus struct {
		getStatus
	}
	h := &getStatusHandler{hdlr}
	return s.Handle(s.NewHandler(&GetStatus{h}, opts...))
}

type getStatusHandler struct {
	GetStatusHandler
}

func (h *getStatusHandler) Status(ctx context.Context, in *GetStatus, out *RetStatus) error {
	return h.GetStatusHandler.Status(ctx, in, out)
}
